import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import contactsRouter from "./contacts";
import eventsRouter from "./events";
import employeesRouter from "./employees";
import dashboardRouter from "./dashboard";
import signupRouter from "./signup";
import googleAuthRouter from "./google-auth";
import gmailRouter from "./gmail";
import calendarRouter from "./calendar";
import usersRouter from "./users";
import commScheduleRouter from "./comm-schedule";
import debriefRouter from "./debrief";
import storageRouter from "./storage";
import payrollRouter from "./payroll";
import myEventsRouter from "./my-events";
import bandsRouter from "./bands";
import bandInvitesRouter from "./band-invites";
import packingRouter from "./packing";
import eventTypesRouter from "./event-types";
import eventStaffingRouter from "./event-staffing";
import ticketsRouter from "./tickets";

const router: IRouter = Router();

router.use(storageRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(contactsRouter);
router.use(eventsRouter);
router.use(employeesRouter);
router.use(dashboardRouter);
router.use(signupRouter);
router.use(googleAuthRouter);
router.use(gmailRouter);
router.use(calendarRouter);
router.use(usersRouter);
router.use(commScheduleRouter);
router.use(debriefRouter);
router.use(payrollRouter);
router.use(myEventsRouter);
router.use(bandsRouter);
router.use(bandInvitesRouter);
router.use(packingRouter);
router.use(eventTypesRouter);
router.use(eventStaffingRouter);
router.use(ticketsRouter);

export default router;
